<?php

// Generated by Haxe 3.3.0
class ufront_core_FutureTools {
	public function __construct(){}
	static function asFuture($data) {
		$GLOBALS['%s']->push("ufront.core.FutureTools::asFuture");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = tink_core__Future_Future_Impl_::sync($data);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	function __toString() { return 'ufront.core.FutureTools'; }
}
