<?php

// Generated by Haxe 3.3.0
class minject_point_ConstructorInjectionPoint extends minject_point_MethodInjectionPoint {
	public function __construct($args) { if(!php_Boot::$skip_constructor) {
		$GLOBALS['%s']->push("minject.point.ConstructorInjectionPoint::new");
		$__hx__spos = $GLOBALS['%s']->length;
		parent::__construct("new",$args);
		$GLOBALS['%s']->pop();
	}}
	public function createInstance($type, $injector) {
		$GLOBALS['%s']->push("minject.point.ConstructorInjectionPoint::createInstance");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = $this->gatherArgs($type, $injector);
		{
			$tmp2 = Type::createInstance($type, $tmp);
			$GLOBALS['%s']->pop();
			return $tmp2;
		}
		$GLOBALS['%s']->pop();
	}
	function __toString() { return 'minject.point.ConstructorInjectionPoint'; }
}
