<?php

// Generated by Haxe 3.3.0
class minject_point_MethodInjectionPoint implements minject_point_InjectionPoint{
	public function __construct($field, $args) {
		if(!php_Boot::$skip_constructor) {
		$GLOBALS['%s']->push("minject.point.MethodInjectionPoint::new");
		$__hx__spos = $GLOBALS['%s']->length;
		$this->field = $field;
		$this->args = $args;
		$GLOBALS['%s']->pop();
	}}
	public $field;
	public $args;
	public function applyInjection($target, $injector) {
		$GLOBALS['%s']->push("minject.point.MethodInjectionPoint::applyInjection");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = Reflect::field($target, $this->field);
		$tmp1 = $this->gatherArgs($target, $injector);
		Reflect::callMethod($target, $tmp, $tmp1);
		{
			$GLOBALS['%s']->pop();
			return $target;
		}
		$GLOBALS['%s']->pop();
	}
	public function gatherArgs($target, $injector) {
		$GLOBALS['%s']->push("minject.point.MethodInjectionPoint::gatherArgs");
		$__hx__spos = $GLOBALS['%s']->length;
		$values = (new _hx_array(array()));
		$index = 0;
		while($index < $this->args->length) {
			$tmp = $index++;
			$type = $this->args[$tmp];
			$tmp1 = $index++;
			$argName = $this->args[$tmp1];
			$tmp2 = $index++;
			$opt = $this->args[$tmp2] === "o";
			$response = $injector->getValueForType($type, $argName);
			$values->push($response);
			$tmp3 = null;
			if(!$opt) {
				$tmp3 = $response === null;
			} else {
				$tmp3 = false;
			}
			if($tmp3) {
				$tmp4 = Type::getClass($target);
				throw new HException("Injector is missing a mapping to handle injection into target \"" . _hx_string_or_null(Type::getClassName($tmp4)) . "\". " . _hx_string_or_null(("Target dependency: \"" . _hx_string_or_null($type) . "\", method: \"" . _hx_string_or_null($this->field) . "\", named: \"" . _hx_string_or_null($argName) . "\"")));
				unset($tmp4);
			}
			unset($type,$tmp3,$tmp2,$tmp1,$tmp,$response,$opt,$argName);
		}
		{
			$GLOBALS['%s']->pop();
			return $values;
		}
		$GLOBALS['%s']->pop();
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return 'minject.point.MethodInjectionPoint'; }
}
