<?php

// Generated by Haxe 3.3.0
class Math {
	public function __construct(){}
	static $PI;
	static $NaN;
	static $POSITIVE_INFINITY;
	static $NEGATIVE_INFINITY;
	static function abs($v) {
		$GLOBALS['%s']->push("Math::abs");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = abs($v);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function min($a, $b) {
		$GLOBALS['%s']->push("Math::min");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = !Math::isNaN($a);
		if($tmp) {
			$tmp2 = min($a, $b);
			$GLOBALS['%s']->pop();
			return $tmp2;
		} else {
			$tmp2 = Math::$NaN;
			$GLOBALS['%s']->pop();
			return $tmp2;
		}
		$GLOBALS['%s']->pop();
	}
	static function max($a, $b) {
		$GLOBALS['%s']->push("Math::max");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = !Math::isNaN($b);
		if($tmp) {
			$tmp2 = max($a, $b);
			$GLOBALS['%s']->pop();
			return $tmp2;
		} else {
			$tmp2 = Math::$NaN;
			$GLOBALS['%s']->pop();
			return $tmp2;
		}
		$GLOBALS['%s']->pop();
	}
	static function sin($v) {
		$GLOBALS['%s']->push("Math::sin");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = sin($v);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function cos($v) {
		$GLOBALS['%s']->push("Math::cos");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = cos($v);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function atan2($y, $x) {
		$GLOBALS['%s']->push("Math::atan2");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = atan2($y, $x);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function tan($v) {
		$GLOBALS['%s']->push("Math::tan");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = tan($v);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function exp($v) {
		$GLOBALS['%s']->push("Math::exp");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = Math::isNaN($v);
		if($tmp) {
			$tmp2 = Math::$NaN;
			$GLOBALS['%s']->pop();
			return $tmp2;
		}
		$tmp1 = is_finite($v);
		if($tmp1) {
			$tmp2 = exp($v);
			$GLOBALS['%s']->pop();
			return $tmp2;
		} else {
			if($v === Math::$POSITIVE_INFINITY) {
				$tmp2 = Math::$POSITIVE_INFINITY;
				$GLOBALS['%s']->pop();
				return $tmp2;
			} else {
				$GLOBALS['%s']->pop();
				return 0.0;
			}
		}
		$GLOBALS['%s']->pop();
	}
	static function log($v) {
		$GLOBALS['%s']->push("Math::log");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = log($v);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function sqrt($v) {
		$GLOBALS['%s']->push("Math::sqrt");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = sqrt($v);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function round($v) {
		$GLOBALS['%s']->push("Math::round");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = (int) floor($v + 0.5);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function floor($v) {
		$GLOBALS['%s']->push("Math::floor");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = (int) floor($v);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function ceil($v) {
		$GLOBALS['%s']->push("Math::ceil");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = (int) ceil($v);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function atan($v) {
		$GLOBALS['%s']->push("Math::atan");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = atan($v);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function asin($v) {
		$GLOBALS['%s']->push("Math::asin");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = asin($v);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function acos($v) {
		$GLOBALS['%s']->push("Math::acos");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = acos($v);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function pow($v, $exp) {
		$GLOBALS['%s']->push("Math::pow");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = pow($v, $exp);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function random() {
		$GLOBALS['%s']->push("Math::random");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = mt_rand();
		$tmp1 = mt_getrandmax();
		{
			$tmp2 = $tmp / $tmp1;
			$GLOBALS['%s']->pop();
			return $tmp2;
		}
		$GLOBALS['%s']->pop();
	}
	static function isNaN($f) {
		$GLOBALS['%s']->push("Math::isNaN");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = is_nan($f);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function isFinite($f) {
		$GLOBALS['%s']->push("Math::isFinite");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = is_finite($f);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function fround($v) {
		$GLOBALS['%s']->push("Math::fround");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = floor($v + 0.5);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function ffloor($v) {
		$GLOBALS['%s']->push("Math::ffloor");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = floor($v);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function fceil($v) {
		$GLOBALS['%s']->push("Math::fceil");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = ceil($v);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	function __toString() { return 'Math'; }
}
{
	Math::$PI = M_PI;
	Math::$NaN = acos(1.01);
	Math::$NEGATIVE_INFINITY = log(0);
	Math::$POSITIVE_INFINITY = -Math::$NEGATIVE_INFINITY;
}
