<?php

// Generated by Haxe 3.3.0
class Std {
	public function __construct(){}
	static function is($v, $t) {
		$GLOBALS['%s']->push("Std::is");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = _hx_instanceof($v, $t);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function instance($value, $c) {
		$GLOBALS['%s']->push("Std::instance");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = Std::is($value, $c);
		if($tmp) {
			$tmp2 = $value;
			$GLOBALS['%s']->pop();
			return $tmp2;
		} else {
			$GLOBALS['%s']->pop();
			return null;
		}
		$GLOBALS['%s']->pop();
	}
	static function string($s) {
		$GLOBALS['%s']->push("Std::string");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = _hx_string_rec($s, "");
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function int($x) {
		$GLOBALS['%s']->push("Std::int");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = fmod($x, -2147483648);
		$i = $tmp & -1;
		$tmp1 = $i & -2147483648;
		if($tmp1) {
			$tmp2 = ~$i & -1;
			$i = -($tmp2 + 1);
		}
		{
			$GLOBALS['%s']->pop();
			return $i;
		}
		$GLOBALS['%s']->pop();
	}
	static function parseInt($x) {
		$GLOBALS['%s']->push("Std::parseInt");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = !is_numeric($x);
		if($tmp) {
			$matches = null;
			preg_match("/^-?\\d+/", $x, $matches);
			$tmp1 = count($matches);
			if($tmp1 === 0) {
				$GLOBALS['%s']->pop();
				return null;
			} else {
				$tmp2 = intval($matches[0]);
				$GLOBALS['%s']->pop();
				return $tmp2;
			}
		} else {
			$tmp2 = strtolower(_hx_substr($x, 0, 2));
			if($tmp2 === "0x") {
				$tmp3 = (int) hexdec(substr($x, 2));
				$GLOBALS['%s']->pop();
				return $tmp3;
			} else {
				$tmp3 = intval($x);
				$GLOBALS['%s']->pop();
				return $tmp3;
			}
		}
		$GLOBALS['%s']->pop();
	}
	static function parseFloat($x) {
		$GLOBALS['%s']->push("Std::parseFloat");
		$__hx__spos = $GLOBALS['%s']->length;
		$v = floatval($x);
		if($v === 0.0) {
			$x = rtrim($x);
			$v = floatval($x);
			$tmp = null;
			if($v === 0.0) {
				$tmp = !is_numeric($x);
			} else {
				$tmp = false;
			}
			if($tmp) {
				$v = acos(1.01);
			}
		}
		{
			$GLOBALS['%s']->pop();
			return $v;
		}
		$GLOBALS['%s']->pop();
	}
	static function random($x) {
		$GLOBALS['%s']->push("Std::random");
		$__hx__spos = $GLOBALS['%s']->length;
		if($x <= 0) {
			$GLOBALS['%s']->pop();
			return 0;
		} else {
			$tmp = mt_rand(0, $x - 1);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	function __toString() { return 'Std'; }
}
