<?php

// Generated by Haxe 3.3.0
class ufront_web_HttpError {
	public function __construct(){}
	static function wrap($e, $msg = null, $pos = null) {
		$GLOBALS['%s']->push("ufront.web.HttpError::wrap");
		$__hx__spos = $GLOBALS['%s']->length;
		if($msg === null) {
			$msg = "Internal Server Error";
		}
		$tmp = Std::is($e, _hx_qtype("tink.core.TypedError"));
		if($tmp) {
			$tmp2 = $e;
			$GLOBALS['%s']->pop();
			return $tmp2;
		} else {
			$tmp2 = tink_core_TypedError::withData(500, $msg, $e, $pos);
			$GLOBALS['%s']->pop();
			return $tmp2;
		}
		$GLOBALS['%s']->pop();
	}
	static function badRequest($reason = null, $pos = null) {
		$GLOBALS['%s']->push("ufront.web.HttpError::badRequest");
		$__hx__spos = $GLOBALS['%s']->length;
		$message = "Bad Request";
		if($reason !== null) {
			$message = "Bad Request" . _hx_string_or_null((": " . _hx_string_or_null($reason)));
		}
		{
			$tmp = new tink_core_TypedError(400, $message, $pos);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function internalServerError($msg = null, $inner = null, $pos = null) {
		$GLOBALS['%s']->push("ufront.web.HttpError::internalServerError");
		$__hx__spos = $GLOBALS['%s']->length;
		if($msg === null) {
			$msg = "Internal Server Error";
		}
		{
			$tmp = tink_core_TypedError::withData(500, $msg, $inner, $pos);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function methodNotAllowed($pos = null) {
		$GLOBALS['%s']->push("ufront.web.HttpError::methodNotAllowed");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = new tink_core_TypedError(405, "Method Not Allowed", $pos);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function pageNotFound($pos = null) {
		$GLOBALS['%s']->push("ufront.web.HttpError::pageNotFound");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = new tink_core_TypedError(404, "Page Not Found", $pos);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function unauthorized($message = null, $pos = null) {
		$GLOBALS['%s']->push("ufront.web.HttpError::unauthorized");
		$__hx__spos = $GLOBALS['%s']->length;
		if($message === null) {
			$message = "Unauthorized Access";
		}
		{
			$tmp = new tink_core_TypedError(401, $message, $pos);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function unprocessableEntity($pos = null) {
		$GLOBALS['%s']->push("ufront.web.HttpError::unprocessableEntity");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = new tink_core_TypedError(422, "Unprocessable Entity", $pos);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function authError($error, $pos = null) {
		$GLOBALS['%s']->push("ufront.web.HttpError::authError");
		$__hx__spos = $GLOBALS['%s']->length;
		$msg = null;
		$tmp = $error->index;
		switch($tmp) {
		case 0:{
			$msg = "Not Logged In";
		}break;
		case 1:{
			$msg = "Login Failed: " . _hx_string_or_null(_hx_deref($error)->params[0]);
		}break;
		case 2:{
			$tmp1 = Std::string(_hx_deref($error)->params[0]);
			$msg = "Not Logged In As " . _hx_string_or_null($tmp1);
		}break;
		case 3:{
			$tmp2 = Std::string(_hx_deref($error)->params[0]);
			$msg = "Permission " . _hx_string_or_null($tmp2) . " denied";
		}break;
		}
		{
			$tmp2 = tink_core_TypedError::typed(401, $msg, $error, $pos);
			$GLOBALS['%s']->pop();
			return $tmp2;
		}
		$GLOBALS['%s']->pop();
	}
	static function remotingError($error, $pos = null) {
		$GLOBALS['%s']->push("ufront.web.HttpError::remotingError");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = $error->index;
		switch($tmp) {
		case 0:{
			$responseCode = _hx_deref($error)->params[1];
			{
				$tmp2 = tink_core_TypedError::typed($responseCode, "HTTP " . _hx_string_rec($responseCode, "") . " Error during " . _hx_string_or_null(_hx_deref($error)->params[0]), $error, $pos);
				$GLOBALS['%s']->pop();
				return $tmp2;
			}
		}break;
		case 1:{
			$tmp2 = tink_core_TypedError::typed(404, "Remoting API " . _hx_string_or_null(_hx_deref($error)->params[0]) . " not found: " . _hx_string_or_null(_hx_deref($error)->params[1]), $error, $pos);
			$GLOBALS['%s']->pop();
			return $tmp2;
		}break;
		case 2:{
			$e = _hx_deref($error)->params[1];
			$remotingCallString = _hx_deref($error)->params[0];
			$errorObj = Std::instance($e, _hx_qtype("tink.core.TypedError"));
			if($errorObj !== null) {
				$tmp2 = tink_core_TypedError::typed($errorObj->code, $errorObj->message, $error, $pos);
				$GLOBALS['%s']->pop();
				return $tmp2;
			} else {
				$tmp2 = tink_core_TypedError::typed(500, "Internal Server Error while executing " . _hx_string_or_null($remotingCallString), $error, $pos);
				$GLOBALS['%s']->pop();
				return $tmp2;
			}
		}break;
		case 3:{
			$e1 = _hx_deref($error)->params[1];
			$tmp1 = "Error during callback after " . _hx_string_or_null(_hx_deref($error)->params[0]) . ": ";
			$tmp2 = Std::string($e1);
			{
				$tmp3 = tink_core_TypedError::typed(500, _hx_string_or_null($tmp1) . _hx_string_or_null($tmp2), $error, $pos);
				$GLOBALS['%s']->pop();
				return $tmp3;
			}
		}break;
		case 4:{
			$tmp2 = tink_core_TypedError::typed(422, "Remoting serialization failed for call " . _hx_string_or_null(_hx_deref($error)->params[0]) . ": could not process " . _hx_string_or_null(_hx_deref($error)->params[1]), $error, $pos);
			$GLOBALS['%s']->pop();
			return $tmp2;
		}break;
		case 5:{
			$tmp2 = tink_core_TypedError::typed(500, "Error with response for " . _hx_string_or_null(_hx_deref($error)->params[0]) . ": no remoting response found", $error, $pos);
			$GLOBALS['%s']->pop();
			return $tmp2;
		}break;
		case 6:{
			$data = _hx_deref($error)->params[1];
			$remotingCallString1 = _hx_deref($error)->params[0];
			$tmp3 = Std::is($data, _hx_qtype("tink.core.TypedError"));
			if($tmp3) {
				$e2 = $data;
				{
					$tmp2 = tink_core_TypedError::typed($e2->code, $e2->message, $error, $e2->pos);
					$GLOBALS['%s']->pop();
					return $tmp2;
				}
			} else {
				$tmp4 = "Call to " . _hx_string_or_null($remotingCallString1) . " failed: ";
				$tmp5 = Std::string($data);
				{
					$tmp2 = tink_core_TypedError::typed(500, _hx_string_or_null($tmp4) . _hx_string_or_null($tmp5), $error, $pos);
					$GLOBALS['%s']->pop();
					return $tmp2;
				}
			}
		}break;
		case 7:{
			$tmp2 = tink_core_TypedError::typed(500, "Unknown exception during remoting call", $error, $pos);
			$GLOBALS['%s']->pop();
			return $tmp2;
		}break;
		}
		$GLOBALS['%s']->pop();
	}
	static function notImplemented($pos = null) {
		$GLOBALS['%s']->push("ufront.web.HttpError::notImplemented");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = new tink_core_TypedError(500, "Internal Server Error: " . _hx_string_or_null((_hx_string_or_null($pos->className) . "." . _hx_string_or_null($pos->methodName))) . " is not implemented on this platform", $pos);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function abstractMethod($pos = null) {
		$GLOBALS['%s']->push("ufront.web.HttpError::abstractMethod");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = new tink_core_TypedError(500, "Internal Server Error: " . _hx_string_or_null((_hx_string_or_null($pos->className) . "." . _hx_string_or_null($pos->methodName))) . " is an abstract method and should be overridden by a subclass", $pos);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function throwIfNull($val, $name = null, $pos = null) {
		$GLOBALS['%s']->push("ufront.web.HttpError::throwIfNull");
		$__hx__spos = $GLOBALS['%s']->length;
		if($name === null) {
			$name = "argument";
		}
		if($val === null) {
			throw new HException(new tink_core_TypedError(500, "" . _hx_string_or_null($name) . " should not be null", $pos));
		}
		$GLOBALS['%s']->pop();
	}
	static function fakePosition($obj, $method, $args = null) {
		$GLOBALS['%s']->push("ufront.web.HttpError::fakePosition");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = Type::getClass($obj);
		{
			$tmp2 = _hx_anonymous(array("methodName" => $method, "lineNumber" => -1, "fileName" => "", "customParams" => $args, "className" => Type::getClassName($tmp)));
			$GLOBALS['%s']->pop();
			return $tmp2;
		}
		$GLOBALS['%s']->pop();
	}
	function __toString() { return 'ufront.web.HttpError'; }
}
