<?php

// Generated by Haxe 3.3.0
class tink_core_OutcomeTools {
	public function __construct(){}
	static function sure($outcome) {
		$GLOBALS['%s']->push("tink.core.OutcomeTools::sure");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = $outcome->index;
		switch($tmp) {
		case 0:{
			$data = _hx_deref($outcome)->params[0];
			{
				$GLOBALS['%s']->pop();
				return $data;
			}
		}break;
		case 1:{
			$failure = _hx_deref($outcome)->params[0];
			$tmp1 = Std::is($failure, _hx_qtype("tink.core.TypedError"));
			if($tmp1) {
				$tmp2 = $failure->throwSelf();
				$GLOBALS['%s']->pop();
				return $tmp2;
			} else {
				throw new HException($failure);
			}
		}break;
		}
		$GLOBALS['%s']->pop();
	}
	static function toOption($outcome) {
		$GLOBALS['%s']->push("tink.core.OutcomeTools::toOption");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = $outcome->index;
		switch($tmp) {
		case 0:{
			$tmp2 = haxe_ds_Option::Some(_hx_deref($outcome)->params[0]);
			$GLOBALS['%s']->pop();
			return $tmp2;
		}break;
		case 1:{
			$tmp2 = haxe_ds_Option::$None;
			$GLOBALS['%s']->pop();
			return $tmp2;
		}break;
		}
		$GLOBALS['%s']->pop();
	}
	static function toOutcome($option, $pos = null) {
		$GLOBALS['%s']->push("tink.core.OutcomeTools::toOutcome");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = $option->index;
		switch($tmp) {
		case 0:{
			$tmp2 = tink_core_Outcome::Success(_hx_deref($option)->params[0]);
			$GLOBALS['%s']->pop();
			return $tmp2;
		}break;
		case 1:{
			$tmp1 = "Some value expected but none found in " . _hx_string_or_null($pos->fileName) . "@line " . _hx_string_rec($pos->lineNumber, "");
			{
				$tmp2 = tink_core_Outcome::Failure(new tink_core_TypedError(404, $tmp1, _hx_anonymous(array("fileName" => "Outcome.hx", "lineNumber" => 37, "className" => "tink.core.OutcomeTools", "methodName" => "toOutcome"))));
				$GLOBALS['%s']->pop();
				return $tmp2;
			}
		}break;
		}
		$GLOBALS['%s']->pop();
	}
	static function orNull($outcome) {
		$GLOBALS['%s']->push("tink.core.OutcomeTools::orNull");
		$__hx__spos = $GLOBALS['%s']->length;
		switch($outcome->index) {
		case 0:{
			$tmp = _hx_deref($outcome)->params[0];
			$GLOBALS['%s']->pop();
			return $tmp;
		}break;
		case 1:{
			$GLOBALS['%s']->pop();
			return null;
		}break;
		}
		$GLOBALS['%s']->pop();
	}
	static function orUse($outcome, $fallback) {
		$GLOBALS['%s']->push("tink.core.OutcomeTools::orUse");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = $outcome->index;
		switch($tmp) {
		case 0:{
			$tmp2 = _hx_deref($outcome)->params[0];
			$GLOBALS['%s']->pop();
			return $tmp2;
		}break;
		case 1:{
			$tmp2 = $fallback();
			$GLOBALS['%s']->pop();
			return $tmp2;
		}break;
		}
		$GLOBALS['%s']->pop();
	}
	static function orTry($outcome, $fallback) {
		$GLOBALS['%s']->push("tink.core.OutcomeTools::orTry");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = $outcome->index;
		switch($tmp) {
		case 0:{
			$GLOBALS['%s']->pop();
			return $outcome;
		}break;
		case 1:{
			$tmp2 = $fallback();
			$GLOBALS['%s']->pop();
			return $tmp2;
		}break;
		}
		$GLOBALS['%s']->pop();
	}
	static function equals($outcome, $to) {
		$GLOBALS['%s']->push("tink.core.OutcomeTools::equals");
		$__hx__spos = $GLOBALS['%s']->length;
		switch($outcome->index) {
		case 0:{
			$tmp = (is_object($_t = _hx_deref($outcome)->params[0]) && ($_t instanceof Enum) ? $_t == $to : _hx_equal($_t, $to));
			$GLOBALS['%s']->pop();
			return $tmp;
		}break;
		case 1:{
			$GLOBALS['%s']->pop();
			return false;
		}break;
		}
		$GLOBALS['%s']->pop();
	}
	static function map($outcome, $transform) {
		$GLOBALS['%s']->push("tink.core.OutcomeTools::map");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = $outcome->index;
		switch($tmp) {
		case 0:{
			$tmp1 = call_user_func_array($transform, array(_hx_deref($outcome)->params[0]));
			{
				$tmp2 = tink_core_Outcome::Success($tmp1);
				$GLOBALS['%s']->pop();
				return $tmp2;
			}
		}break;
		case 1:{
			$tmp2 = tink_core_Outcome::Failure(_hx_deref($outcome)->params[0]);
			$GLOBALS['%s']->pop();
			return $tmp2;
		}break;
		}
		$GLOBALS['%s']->pop();
	}
	static function isSuccess($outcome) {
		$GLOBALS['%s']->push("tink.core.OutcomeTools::isSuccess");
		$__hx__spos = $GLOBALS['%s']->length;
		if($outcome->index === 0) {
			$GLOBALS['%s']->pop();
			return true;
		} else {
			$GLOBALS['%s']->pop();
			return false;
		}
		$GLOBALS['%s']->pop();
	}
	static function flatMap($o, $mapper) {
		$GLOBALS['%s']->push("tink.core.OutcomeTools::flatMap");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = tink_core__Outcome_OutcomeMapper_Impl_::apply($mapper, $o);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function attempt($f, $report) {
		$GLOBALS['%s']->push("tink.core.OutcomeTools::attempt");
		$__hx__spos = $GLOBALS['%s']->length;
		try {
			$tmp = call_user_func($f);
			{
				$tmp2 = tink_core_Outcome::Success($tmp);
				$GLOBALS['%s']->pop();
				return $tmp2;
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e = $_ex_;
			{
				$GLOBALS['%e'] = (new _hx_array(array()));
				while($GLOBALS['%s']->length >= $__hx__spos) {
					$GLOBALS['%e']->unshift($GLOBALS['%s']->pop());
				}
				$GLOBALS['%s']->push($GLOBALS['%e'][0]);
				$tmp1 = call_user_func_array($report, array($e));
				{
					$tmp = tink_core_Outcome::Failure($tmp1);
					$GLOBALS['%s']->pop();
					return $tmp;
				}
			}
		}
		$GLOBALS['%s']->pop();
	}
	function __toString() { return 'tink.core.OutcomeTools'; }
}
