<?php

// Generated by Haxe 3.3.0
class ufront_cache_RequestCacheMiddleware implements ufront_app_UFMiddleware{
	public function __construct() {
		if(!php_Boot::$skip_constructor) {
		$GLOBALS['%s']->push("ufront.cache.RequestCacheMiddleware::new");
		$__hx__spos = $GLOBALS['%s']->length;
		$GLOBALS['%s']->pop();
	}}
	public $cacheConnection;
	public $cache;
	public function requestIn($ctx) {
		$GLOBALS['%s']->push("ufront.cache.RequestCacheMiddleware::requestIn");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = ufront_core_SurpriseTools::success();
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	public function responseOut($ctx) {
		$GLOBALS['%s']->push("ufront.cache.RequestCacheMiddleware::responseOut");
		$__hx__spos = $GLOBALS['%s']->length;
		if($this->cache === null) {
			$this->cache = $this->cacheConnection->getNamespace("ufront.middleware.RequestCache");
		}
		$tmp = null;
		$tmp1 = null;
		$tmp2 = null;
		$tmp3 = strtolower($ctx->request->get_httpMethod());
		if($tmp3 === "get") {
			$tmp2 = $ctx->actionContext !== null;
		} else {
			$tmp2 = false;
		}
		if($tmp2) {
			$tmp1 = _hx_field($ctx->actionContext, "controller") !== null;
		} else {
			$tmp1 = false;
		}
		if($tmp1) {
			$tmp = $ctx->actionContext->action !== null;
		} else {
			$tmp = false;
		}
		if($tmp) {
			$tmp4 = $ctx->response->get_contentType();
			$tmp5 = ufront_cache_RequestCacheMiddleware::$contentTypesToCache->indexOf($tmp4, null);
			if($tmp5 > -1) {
				$cls = Type::getClass($ctx->actionContext->controller);
				$controllerMeta = haxe_rtti_Meta::getType($cls);
				$tmp6 = haxe_rtti_Meta::getFields($cls);
				$fieldMeta = Reflect::field($tmp6, $ctx->actionContext->action);
				$tmp7 = null;
				$tmp8 = !ufront_cache_RequestCacheMiddleware::hasCacheMeta($controllerMeta);
				if($tmp8) {
					$tmp7 = ufront_cache_RequestCacheMiddleware::hasCacheMeta($fieldMeta);
				} else {
					$tmp7 = true;
				}
				if($tmp7) {
					$uri = $ctx->request->get_uri();
					$f = tink_core__Future_Future_Impl_::sync($ctx->response);
					$tmp9 = $this->cache->set($uri, $f);
					{
						$tmp10 = tink_core__Future_Future_Impl_::_map($tmp9, array(new _hx_lambda(array(&$ctx, &$uri), "ufront_cache_RequestCacheMiddleware_0"), 'execute'));
						$GLOBALS['%s']->pop();
						return $tmp10;
					}
				}
			}
		}
		{
			$tmp4 = ufront_core_SurpriseTools::success();
			$GLOBALS['%s']->pop();
			return $tmp4;
		}
		$GLOBALS['%s']->pop();
	}
	public function invalidate() {
		$GLOBALS['%s']->push("ufront.cache.RequestCacheMiddleware::invalidate");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = $this->cache->clear();
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	static function __meta__() { $args = func_get_args(); return call_user_func_array(self::$__meta__, $args); }
	static $__meta__;
	static $hnamespace = "ufront.middleware.RequestCache";
	static $metaName = "cacheRequest";
	static $contentTypesToCache;
	static function hasCacheMeta($meta) {
		$GLOBALS['%s']->push("ufront.cache.RequestCacheMiddleware::hasCacheMeta");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = _hx_has_field($meta, ufront_cache_RequestCacheMiddleware::$metaName);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	function __toString() { return 'ufront.cache.RequestCacheMiddleware'; }
}
ufront_cache_RequestCacheMiddleware::$__meta__ = _hx_anonymous(array("obj" => _hx_anonymous(array("rtti" => (new _hx_array(array((new _hx_array(array("cacheConnection", "ufront.cache.UFCacheConnection", ""))))))))));
ufront_cache_RequestCacheMiddleware::$contentTypesToCache = (new _hx_array(array("text/plain", "text/html", "text/xml", "text/css", "text/csv", "application/json", "application/javascript", "application/atom+xml", "application/rdf+xml", "application/rss+xml", "application/soap+xml", "application/xhtml+xml", "application/xml", "application/xml-dtd")));
function ufront_cache_RequestCacheMiddleware_0(&$ctx, &$uri, $result) {
	{
		$GLOBALS['%s']->push("ufront.cache.RequestCacheMiddleware::responseOut@117");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp10 = $result->index === 1;
		if($tmp10) {
			$e = _hx_deref($result)->params[0];
			$tmp11 = "Failed to save cache for " . _hx_string_or_null($uri) . ": ";
			$tmp12 = Std::string($e);
			$ctx->messages->push(_hx_anonymous(array("msg" => _hx_string_or_null($tmp11) . _hx_string_or_null($tmp12), "pos" => _hx_anonymous(array("fileName" => "RequestCacheMiddleware.hx", "lineNumber" => 121, "className" => "ufront.cache.RequestCacheMiddleware", "methodName" => "responseOut")), "type" => ufront_log_MessageType::$MError)));
		}
		{
			$tmp = tink_core_Outcome::Success(tink_core_Noise::$Noise);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
