<?php

// Generated by Haxe 3.3.0
class ufront_core__CaseInsensitiveMultiValueMap_CaseInsensitiveMultiValueMap_Impl_ {
	public function __construct(){}
	static function _new() {
		$GLOBALS['%s']->push("ufront.core._CaseInsensitiveMultiValueMap.CaseInsensitiveMultiValueMap_Impl_::_new");
		$__hx__spos = $GLOBALS['%s']->length;
		$this1 = null;
		$this2 = new haxe_ds_StringMap();
		$this1 = $this2;
		{
			$tmp = $this1;
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function exists($this1, $name) {
		$GLOBALS['%s']->push("ufront.core._CaseInsensitiveMultiValueMap.CaseInsensitiveMultiValueMap_Impl_::exists");
		$__hx__spos = $GLOBALS['%s']->length;
		$name1 = strtolower($name);
		{
			$tmp = $this1->exists($name1);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function getAll($this1, $name) {
		$GLOBALS['%s']->push("ufront.core._CaseInsensitiveMultiValueMap.CaseInsensitiveMultiValueMap_Impl_::getAll");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = strtolower($name);
		{
			$tmp2 = ufront_core__MultiValueMap_MultiValueMap_Impl_::getAll($this1, $tmp);
			$GLOBALS['%s']->pop();
			return $tmp2;
		}
		$GLOBALS['%s']->pop();
	}
	static function get($this1, $name) {
		$GLOBALS['%s']->push("ufront.core._CaseInsensitiveMultiValueMap.CaseInsensitiveMultiValueMap_Impl_::get");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = strtolower($name);
		{
			$tmp2 = ufront_core__MultiValueMap_MultiValueMap_Impl_::get($this1, $tmp);
			$GLOBALS['%s']->pop();
			return $tmp2;
		}
		$GLOBALS['%s']->pop();
	}
	static function set($this1, $name, $value) {
		$GLOBALS['%s']->push("ufront.core._CaseInsensitiveMultiValueMap.CaseInsensitiveMultiValueMap_Impl_::set");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = strtolower($name);
		ufront_core__MultiValueMap_MultiValueMap_Impl_::set($this1, $tmp, $value);
		$GLOBALS['%s']->pop();
	}
	static function add($this1, $name, $value) {
		$GLOBALS['%s']->push("ufront.core._CaseInsensitiveMultiValueMap.CaseInsensitiveMultiValueMap_Impl_::add");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = strtolower($name);
		ufront_core__MultiValueMap_MultiValueMap_Impl_::add($this1, $tmp, $value);
		$GLOBALS['%s']->pop();
	}
	static function remove($this1, $key) {
		$GLOBALS['%s']->push("ufront.core._CaseInsensitiveMultiValueMap.CaseInsensitiveMultiValueMap_Impl_::remove");
		$__hx__spos = $GLOBALS['%s']->length;
		$key1 = strtolower($key);
		{
			$tmp = $this1->remove($key1);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	static function hclone($this1) {
		$GLOBALS['%s']->push("ufront.core._CaseInsensitiveMultiValueMap.CaseInsensitiveMultiValueMap_Impl_::clone");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = ufront_core__MultiValueMap_MultiValueMap_Impl_::hclone($this1);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	function __toString() { return 'ufront.core._CaseInsensitiveMultiValueMap.CaseInsensitiveMultiValueMap_Impl_'; }
}
