<?php

// Generated by Haxe 3.3.0
class ufront_api_UFCallbackApi {
	public function __construct() {
		if(!php_Boot::$skip_constructor) {
		$GLOBALS['%s']->push("ufront.api.UFCallbackApi::new");
		$__hx__spos = $GLOBALS['%s']->length;
		$GLOBALS['%s']->pop();
	}}
	public $className;
	public $api;
	public function _makeApiCall($method, $args, $flags, $onResult, $onError = null) {
		$GLOBALS['%s']->push("ufront.api.UFCallbackApi::_makeApiCall");
		$__hx__spos = $GLOBALS['%s']->length;
		$_gthis = $this;
		if($this->className === null) {
			$tmp = Type::getClass($this);
			$this->className = Type::getClassName($tmp);
		}
		$tmp1 = "" . _hx_string_or_null($this->className) . "." . _hx_string_or_null($method) . "(";
		$tmp2 = $args->join(",");
		$remotingCallString = _hx_string_or_null($tmp1) . _hx_string_or_null($tmp2) . ")";
		$callApi = array(new _hx_lambda(array(&$_gthis, &$args, &$method), "ufront_api_UFCallbackApi_0"), 'execute');
		$processError = array(new _hx_lambda(array(&$onError, &$remotingCallString), "ufront_api_UFCallbackApi_1"), 'execute');
		$tmp5 = $onError === null;
		if($tmp5) {
			$onError = array(new _hx_lambda(array(), "ufront_api_UFCallbackApi_2"), 'execute');
		}
		$tmp6 = $flags & 1 << ufront_api_ApiReturnType::$ARTVoid->index;
		if($tmp6 !== 0) {
			try {
				call_user_func($callApi);
				$onResult(null);
			}catch(Exception $__hx__e) {
				$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
				$e1 = $_ex_;
				{
					$GLOBALS['%e'] = (new _hx_array(array()));
					while($GLOBALS['%s']->length >= $__hx__spos) {
						$GLOBALS['%e']->unshift($GLOBALS['%s']->pop());
					}
					$GLOBALS['%s']->push($GLOBALS['%e'][0]);
					call_user_func_array($processError, array($e1));
				}
			}
		} else {
			$tmp7 = null;
			if(($flags & 1 << ufront_api_ApiReturnType::$ARTFuture->index) !== 0) {
				$tmp7 = ($flags & 1 << ufront_api_ApiReturnType::$ARTOutcome->index) !== 0;
			} else {
				$tmp7 = false;
			}
			if($tmp7) {
				try {
					$surprise = call_user_func($callApi);
					$surprise(array(new _hx_lambda(array(&$onError, &$onResult, &$remotingCallString), "ufront_api_UFCallbackApi_3"), 'execute'));
				}catch(Exception $__hx__e) {
					$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
					$e2 = $_ex_;
					{
						$GLOBALS['%e'] = (new _hx_array(array()));
						while($GLOBALS['%s']->length >= $__hx__spos) {
							$GLOBALS['%e']->unshift($GLOBALS['%s']->pop());
						}
						$GLOBALS['%s']->push($GLOBALS['%e'][0]);
						call_user_func_array($processError, array($e2));
					}
				}
			} else {
				$tmp9 = $flags & 1 << ufront_api_ApiReturnType::$ARTFuture->index;
				if($tmp9 !== 0) {
					try {
						$future = call_user_func($callApi);
						$future(array(new _hx_lambda(array(&$onResult), "ufront_api_UFCallbackApi_4"), 'execute'));
					}catch(Exception $__hx__e) {
						$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
						$e3 = $_ex_;
						{
							$GLOBALS['%e'] = (new _hx_array(array()));
							while($GLOBALS['%s']->length >= $__hx__spos) {
								$GLOBALS['%e']->unshift($GLOBALS['%s']->pop());
							}
							$GLOBALS['%s']->push($GLOBALS['%e'][0]);
							call_user_func_array($processError, array($e3));
						}
					}
				} else {
					$tmp10 = $flags & 1 << ufront_api_ApiReturnType::$ARTOutcome->index;
					if($tmp10 !== 0) {
						try {
							$outcome = call_user_func($callApi);
							$tmp11 = $outcome->index;
							switch($tmp11) {
							case 0:{
								$onResult(_hx_deref($outcome)->params[0]);
							}break;
							case 1:{
								$data3 = ufront_remoting_RemotingError::RApiFailure($remotingCallString, _hx_deref($outcome)->params[0]);
								$onError($data3);
							}break;
							}
						}catch(Exception $__hx__e) {
							$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
							$e4 = $_ex_;
							{
								$GLOBALS['%e'] = (new _hx_array(array()));
								while($GLOBALS['%s']->length >= $__hx__spos) {
									$GLOBALS['%e']->unshift($GLOBALS['%s']->pop());
								}
								$GLOBALS['%s']->push($GLOBALS['%e'][0]);
								call_user_func_array($processError, array($e4));
							}
						}
					} else {
						try {
							$result1 = call_user_func($callApi);
							$onResult($result1);
						}catch(Exception $__hx__e) {
							$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
							$e5 = $_ex_;
							{
								$GLOBALS['%e'] = (new _hx_array(array()));
								while($GLOBALS['%s']->length >= $__hx__spos) {
									$GLOBALS['%e']->unshift($GLOBALS['%s']->pop());
								}
								$GLOBALS['%s']->push($GLOBALS['%e'][0]);
								call_user_func_array($processError, array($e5));
							}
						}
					}
				}
			}
		}
		$GLOBALS['%s']->pop();
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	static function getCallbackApi($syncApi) {
		$GLOBALS['%s']->push("ufront.api.UFCallbackApi::getCallbackApi");
		$__hx__spos = $GLOBALS['%s']->length;
		$meta = haxe_rtti_Meta::getType($syncApi);
		if($meta->callbackApi !== null) {
			$asyncCallbackApiName = $meta->callbackApi[0];
			if($asyncCallbackApiName !== null) {
				$tmp = Type::resolveClass($asyncCallbackApiName);
				$GLOBALS['%s']->pop();
				return $tmp;
			}
		}
		{
			$GLOBALS['%s']->pop();
			return null;
		}
		$GLOBALS['%s']->pop();
	}
	function __toString() { return 'ufront.api.UFCallbackApi'; }
}
function ufront_api_UFCallbackApi_0(&$_gthis, &$args, &$method) {
	{
		$GLOBALS['%s']->push("ufront.api.UFCallbackApi::_makeApiCall@111");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp3 = Reflect::field($_gthis->api, $method);
		{
			$tmp = Reflect::callMethod($_gthis->api, $tmp3, $args);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_api_UFCallbackApi_1(&$onError, &$remotingCallString, $e) {
	{
		$GLOBALS['%s']->push("ufront.api.UFCallbackApi::_makeApiCall@114");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp4 = haxe_CallStack::exceptionStack();
		$stack = haxe_CallStack::toString($tmp4);
		{
			$data = ufront_remoting_RemotingError::RServerSideException($remotingCallString, $e, $stack);
			$onError($data);
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_api_UFCallbackApi_2($err) {
	{
		$GLOBALS['%s']->push("ufront.api.UFCallbackApi::_makeApiCall@119");
		$__hx__spos = $GLOBALS['%s']->length;
		$GLOBALS['%s']->pop();
	}
}
function ufront_api_UFCallbackApi_3(&$onError, &$onResult, &$remotingCallString, $result) {
	{
		$GLOBALS['%s']->push("ufront.api.UFCallbackApi::_makeApiCall@132");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp8 = $result->index;
		switch($tmp8) {
		case 0:{
			$onResult(_hx_deref($result)->params[0]);
		}break;
		case 1:{
			$data1 = ufront_remoting_RemotingError::RApiFailure($remotingCallString, _hx_deref($result)->params[0]);
			$onError($data1);
		}break;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_api_UFCallbackApi_4(&$onResult, $data2) {
	{
		$GLOBALS['%s']->push("ufront.api.UFCallbackApi::_makeApiCall@142");
		$__hx__spos = $GLOBALS['%s']->length;
		$onResult($data2);
		$GLOBALS['%s']->pop();
	}
}
