<?php

// Generated by Haxe 3.3.0
class ufront_app_HttpApplication {
	public function __construct() {
		if(!php_Boot::$skip_constructor) {
		$GLOBALS['%s']->push("ufront.app.HttpApplication::new");
		$__hx__spos = $GLOBALS['%s']->length;
		$this->pathToContentDir = null;
		$this->requestMiddleware = (new _hx_array(array()));
		$this->requestHandlers = (new _hx_array(array()));
		$this->responseMiddleware = (new _hx_array(array()));
		$this->logHandlers = (new _hx_array(array()));
		$this->errorHandlers = (new _hx_array(array()));
		$this->urlFilters = (new _hx_array(array()));
		$this->messages = (new _hx_array(array()));
		$this->injector = new minject_Injector(null);
		$this->injector->mapType("minject.Injector", null, null)->toValue($this->injector);
		$GLOBALS['%s']->pop();
	}}
	public $injector;
	public $requestMiddleware;
	public $requestHandlers;
	public $responseMiddleware;
	public $logHandlers;
	public $errorHandlers;
	public $urlFilters;
	public $originalTrace;
	public $messages;
	public $modulesReady;
	public $currentModule;
	public $pathToContentDir;
	public function init() {
		$GLOBALS['%s']->push("ufront.app.HttpApplication::init");
		$__hx__spos = $GLOBALS['%s']->length;
		$_gthis = $this;
		$this->originalTrace = (isset(haxe_Log::$trace) ? haxe_Log::$trace: array("haxe_Log", "trace"));
		haxe_Log::$trace = array(new _hx_lambda(array(&$_gthis), "ufront_app_HttpApplication_0"), 'execute');
		if($this->modulesReady === null) {
			$futures = (new _hx_array(array()));
			{
				$_g = 0;
				$_g1 = $this->getModulesThatRequireInit();
				while($_g < $_g1->length) {
					$module = $_g1[$_g];
					++$_g;
					$tmp = $module->init($this);
					$futures->push($tmp);
					unset($tmp,$module);
				}
			}
			$tmp1 = tink_core__Future_Future_Impl_::ofMany($futures, null);
			$this->modulesReady = tink_core__Future_Future_Impl_::map($tmp1, array(new _hx_lambda(array(), "ufront_app_HttpApplication_1"), 'execute'), null);
		}
		{
			$tmp = (isset($this->modulesReady) ? $this->modulesReady: array($this, "modulesReady"));
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	public function dispose() {
		$GLOBALS['%s']->push("ufront.app.HttpApplication::dispose");
		$__hx__spos = $GLOBALS['%s']->length;
		$_gthis = $this;
		$futures = (new _hx_array(array()));
		{
			$_g = 0;
			$_g1 = $this->getModulesThatRequireInit();
			while($_g < $_g1->length) {
				$module = $_g1[$_g];
				++$_g;
				$tmp = $module->dispose($this);
				$futures->push($tmp);
				unset($tmp,$module);
			}
		}
		$tmp1 = tink_core__Future_Future_Impl_::ofMany($futures, null);
		{
			$tmp = tink_core__Future_Future_Impl_::map($tmp1, array(new _hx_lambda(array(&$_gthis), "ufront_app_HttpApplication_2"), 'execute'), null);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	public function getModulesThatRequireInit() {
		$GLOBALS['%s']->push("ufront.app.HttpApplication::getModulesThatRequireInit");
		$__hx__spos = $GLOBALS['%s']->length;
		$moduleSets = (new _hx_array(array($this->requestMiddleware, $this->requestHandlers, $this->responseMiddleware, $this->logHandlers, $this->errorHandlers)));
		$modules = (new _hx_array(array()));
		{
			$_g = 0;
			while($_g < $moduleSets->length) {
				$set = $moduleSets[$_g];
				++$_g;
				{
					$_g1 = 0;
					while($_g1 < $set->length) {
						$module = $set[$_g1];
						++$_g1;
						$tmp = Std::is($module, _hx_qtype("ufront.app.UFInitRequired"));
						if($tmp) {
							$modules->push($module);
						}
						unset($tmp,$module);
					}
					unset($_g1);
				}
				unset($set);
			}
		}
		{
			$GLOBALS['%s']->pop();
			return $modules;
		}
		$GLOBALS['%s']->pop();
	}
	public function addRequestMiddleware($middlewareItem = null, $middleware = null, $first = null) {
		$GLOBALS['%s']->push("ufront.app.HttpApplication::addRequestMiddleware");
		$__hx__spos = $GLOBALS['%s']->length;
		if($first === null) {
			$first = false;
		}
		{
			$tmp = $this->addModule($this->requestMiddleware, $middlewareItem, $middleware, $first);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	public function addRequestHandler($handler = null, $handlers = null, $first = null) {
		$GLOBALS['%s']->push("ufront.app.HttpApplication::addRequestHandler");
		$__hx__spos = $GLOBALS['%s']->length;
		if($first === null) {
			$first = false;
		}
		{
			$tmp = $this->addModule($this->requestHandlers, $handler, $handlers, $first);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	public function addErrorHandler($handler = null, $handlers = null, $first = null) {
		$GLOBALS['%s']->push("ufront.app.HttpApplication::addErrorHandler");
		$__hx__spos = $GLOBALS['%s']->length;
		if($first === null) {
			$first = false;
		}
		{
			$tmp = $this->addModule($this->errorHandlers, $handler, $handlers, $first);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	public function addResponseMiddleware($middlewareItem = null, $middleware = null, $last = null) {
		$GLOBALS['%s']->push("ufront.app.HttpApplication::addResponseMiddleware");
		$__hx__spos = $GLOBALS['%s']->length;
		if($last === null) {
			$last = false;
		}
		{
			$tmp = $this->addModule($this->responseMiddleware, $middlewareItem, $middleware, !$last);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	public function addMiddleware($middlewareItem = null, $middleware = null, $firstInLastOut = null) {
		$GLOBALS['%s']->push("ufront.app.HttpApplication::addMiddleware");
		$__hx__spos = $GLOBALS['%s']->length;
		if($firstInLastOut === null) {
			$firstInLastOut = false;
		}
		$this->addModule($this->requestMiddleware, $middlewareItem, $middleware, $firstInLastOut);
		$this->addModule($this->responseMiddleware, $middlewareItem, $middleware, !$firstInLastOut);
		{
			$GLOBALS['%s']->pop();
			return $this;
		}
		$GLOBALS['%s']->pop();
	}
	public function addLogHandler($logger = null, $loggers = null, $first = null) {
		$GLOBALS['%s']->push("ufront.app.HttpApplication::addLogHandler");
		$__hx__spos = $GLOBALS['%s']->length;
		if($first === null) {
			$first = false;
		}
		{
			$tmp = $this->addModule($this->logHandlers, $logger, $loggers, $first);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	public function addModule($modulesArr, $newModule = null, $newModules = null, $first) {
		$GLOBALS['%s']->push("ufront.app.HttpApplication::addModule");
		$__hx__spos = $GLOBALS['%s']->length;
		if($newModule !== null) {
			$this->injector->injectInto($newModule);
			if($first) {
				$modulesArr->unshift($newModule);
			} else {
				$modulesArr->push($newModule);
			}
		}
		if($newModules !== null) {
			$tmp = $newModules->iterator();
			while(true) {
				$tmp1 = !$tmp->hasNext();
				if($tmp1) {
					break;
				}
				$newModule1 = $tmp->next();
				$this->injector->injectInto($newModule1);
				if($first) {
					$modulesArr->unshift($newModule1);
				} else {
					$modulesArr->push($newModule1);
				}
				unset($tmp1,$newModule1);
			}
		}
		{
			$GLOBALS['%s']->pop();
			return $this;
		}
		$GLOBALS['%s']->pop();
	}
	public function execute($httpContext) {
		$GLOBALS['%s']->push("ufront.app.HttpApplication::execute");
		$__hx__spos = $GLOBALS['%s']->length;
		$_gthis = $this;
		$httpContext->setUrlFilters($this->urlFilters);
		$reqMidModules = $this->requestMiddleware->map(array(new _hx_lambda(array(), "ufront_app_HttpApplication_3"), 'execute'));
		$reqHandModules = $this->requestHandlers->map(array(new _hx_lambda(array(), "ufront_app_HttpApplication_4"), 'execute'));
		$resMidModules = $this->responseMiddleware->map(array(new _hx_lambda(array(), "ufront_app_HttpApplication_5"), 'execute'));
		$logHandModules = $this->logHandlers->map(array(new _hx_lambda(array(&$_gthis), "ufront_app_HttpApplication_6"), 'execute'));
		$httpContext->getRequestUri();
		$tmp8 = $this->init();
		$allDone = tink_core__Future_Future_Impl_::_tryFailingFlatMap($tmp8, array(new _hx_lambda(array(&$_gthis, &$httpContext, &$logHandModules, &$reqHandModules, &$reqMidModules, &$resMidModules), "ufront_app_HttpApplication_7"), 'execute'));
		{
			$f4 = array(new _hx_lambda(array(&$httpContext), "ufront_app_HttpApplication_8"), 'execute');
			$this5 = array(new _hx_lambda(array(&$f4), "ufront_app_HttpApplication_9"), 'execute');
			$allDone($this5);
		}
		$tmp14 = $httpContext->completion & 1 << ufront_web_context_RequestCompletion::$CFlushComplete->index;
		if(($tmp14 !== 0) === false) {
			$tmp15 = $httpContext->getRequestUri();
			throw new HException("Async callbacks never completed for URI " . _hx_string_or_null($tmp15) . ":  " . _hx_string_or_null(("The last active module was " . _hx_string_or_null($this->currentModule->className) . "." . _hx_string_or_null($this->currentModule->methodName))));
		}
		{
			$GLOBALS['%s']->pop();
			return $allDone;
		}
		$GLOBALS['%s']->pop();
	}
	public function logModule($ctx, $msg) {
		$GLOBALS['%s']->push("ufront.app.HttpApplication::logModule");
		$__hx__spos = $GLOBALS['%s']->length;
		$GLOBALS['%s']->pop();
	}
	public function executeModules($modules, $ctx, $flag) {
		$GLOBALS['%s']->push("ufront.app.HttpApplication::executeModules");
		$__hx__spos = $GLOBALS['%s']->length;
		$_gthis = $this;
		$done = new tink_core_FutureTrigger();
		$runNext = null;
		$runNext = array(new _hx_lambda(array(&$_gthis, &$ctx, &$done, &$flag, &$modules, &$runNext), "ufront_app_HttpApplication_10"), 'execute');
		call_user_func($runNext);
		{
			$tmp = (isset($done->future) ? $done->future: array($done, "future"));
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	public function handleError($err, $ctx, $doneTrigger) {
		$GLOBALS['%s']->push("ufront.app.HttpApplication::handleError");
		$__hx__spos = $GLOBALS['%s']->length;
		$_gthis = $this;
		$tmp = $ctx->completion & 1 << ufront_web_context_RequestCompletion::$CErrorHandlersTriggered->index;
		if($tmp === 0) {
			$ctx->completion |= 1 << ufront_web_context_RequestCompletion::$CErrorHandlersTriggered->index;
			$errHandlerModules = $this->errorHandlers->map(array(new _hx_lambda(array(&$err), "ufront_app_HttpApplication_11"), 'execute'));
			$resMidModules = $this->responseMiddleware->map(array(new _hx_lambda(array(), "ufront_app_HttpApplication_12"), 'execute'));
			$logHandModules = $this->logHandlers->map(array(new _hx_lambda(array(&$_gthis), "ufront_app_HttpApplication_13"), 'execute'));
			$tmp8 = $this->executeModules($errHandlerModules, $ctx, ufront_web_context_RequestCompletion::$CErrorHandlersComplete);
			$tmp9 = tink_core__Future_Future_Impl_::_tryFailingFlatMap($tmp8, array(new _hx_lambda(array(&$ctx), "ufront_app_HttpApplication_14"), 'execute'));
			$allDone = tink_core__Future_Future_Impl_::_tryFailingFlatMap($tmp9, array(new _hx_lambda(array(&$_gthis, &$ctx, &$logHandModules, &$resMidModules), "ufront_app_HttpApplication_15"), 'execute'));
			{
				$f3 = array(new _hx_lambda(array(&$doneTrigger, &$err), "ufront_app_HttpApplication_16"), 'execute');
				$this4 = array(new _hx_lambda(array(&$f3), "ufront_app_HttpApplication_17"), 'execute');
				$allDone($this4);
			}
		} else {
			Sys::println("You had an error after your error handler had already run.  Last active module: " . _hx_string_or_null($this->currentModule->className) . "." . _hx_string_or_null($this->currentModule->methodName));
			$tmp13 = Std::string($err->data);
			Sys::println("Error Data: " . _hx_string_or_null($tmp13));
			$err->throwSelf();
		}
		$GLOBALS['%s']->pop();
	}
	public function clearMessages() {
		$GLOBALS['%s']->push("ufront.app.HttpApplication::clearMessages");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$_g1 = 0;
			$_g = $this->messages->length;
			while($_g1 < $_g) {
				++$_g1;
				$this->messages->pop();
			}
		}
		{
			$tmp = ufront_core_SurpriseTools::success();
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	public function flush($ctx) {
		$GLOBALS['%s']->push("ufront.app.HttpApplication::flush");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = $ctx->completion & 1 << ufront_web_context_RequestCompletion::$CFlushComplete->index;
		if($tmp === 0) {
			$ctx->response->flush();
			$ctx->completion |= 1 << ufront_web_context_RequestCompletion::$CFlushComplete->index;
		}
		{
			$tmp2 = tink_core_Noise::$Noise;
			$GLOBALS['%s']->pop();
			return $tmp2;
		}
		$GLOBALS['%s']->pop();
	}
	public function executeRequest() {
		$GLOBALS['%s']->push("ufront.app.HttpApplication::executeRequest");
		$__hx__spos = $GLOBALS['%s']->length;
		$context = null;
		if($this->pathToContentDir !== null) {
			$context = ufront_web_context_HttpContext::createContext(null, null, $this->injector, null, null, $this->urlFilters, $this->pathToContentDir);
		} else {
			$context = ufront_web_context_HttpContext::createContext(null, null, $this->injector, null, null, $this->urlFilters, null);
		}
		{
			$tmp = $this->execute($context);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
	public function useModNekoCache() {
		$GLOBALS['%s']->push("ufront.app.HttpApplication::useModNekoCache");
		$__hx__spos = $GLOBALS['%s']->length;
		$GLOBALS['%s']->pop();
	}
	public function addUrlFilter($filter) {
		$GLOBALS['%s']->push("ufront.app.HttpApplication::addUrlFilter");
		$__hx__spos = $GLOBALS['%s']->length;
		ufront_web_HttpError::throwIfNull($filter, "filter", _hx_anonymous(array("fileName" => "HttpApplication.hx", "lineNumber" => 619, "className" => "ufront.app.HttpApplication", "methodName" => "addUrlFilter")));
		$this->urlFilters->push($filter);
		$GLOBALS['%s']->pop();
	}
	public function clearUrlFilters() {
		$GLOBALS['%s']->push("ufront.app.HttpApplication::clearUrlFilters");
		$__hx__spos = $GLOBALS['%s']->length;
		$this->urlFilters = (new _hx_array(array()));
		$GLOBALS['%s']->pop();
	}
	public function setContentDirectory($relativePath) {
		$GLOBALS['%s']->push("ufront.app.HttpApplication::setContentDirectory");
		$__hx__spos = $GLOBALS['%s']->length;
		$this->pathToContentDir = $relativePath;
		$GLOBALS['%s']->pop();
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	function __toString() { return 'ufront.app.HttpApplication'; }
}
function ufront_app_HttpApplication_0(&$_gthis, $msg, $pos) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::init@174");
		$__hx__spos = $GLOBALS['%s']->length;
		$_gthis->messages->push(_hx_anonymous(array("msg" => $msg, "pos" => $pos, "type" => ufront_log_MessageType::$MTrace)));
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_1($outcomes) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::init@182");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$_g2 = 0;
			while($_g2 < $outcomes->length) {
				$o = $outcomes[$_g2];
				++$_g2;
				$tmp2 = $o->index;
				switch($tmp2) {
				case 0:{}break;
				case 1:{
					$tmp = tink_core_Outcome::Failure(_hx_deref($o)->params[0]);
					$GLOBALS['%s']->pop();
					return $tmp;
				}break;
				}
				unset($tmp2,$o);
			}
		}
		{
			$tmp = tink_core_Outcome::Success(tink_core_Noise::$Noise);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_2(&$_gthis, $outcomes) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::dispose@202");
		$__hx__spos = $GLOBALS['%s']->length;
		$_gthis->modulesReady = null;
		{
			$_g2 = 0;
			while($_g2 < $outcomes->length) {
				$o = $outcomes[$_g2];
				++$_g2;
				switch($o->index) {
				case 0:{}break;
				case 1:{
					$GLOBALS['%s']->pop();
					return $o;
				}break;
				}
				unset($o);
			}
		}
		haxe_Log::$trace = (isset($_gthis->originalTrace) ? $_gthis->originalTrace: array($_gthis, "originalTrace"));
		{
			$tmp = tink_core_Outcome::Success(tink_core_Noise::$Noise);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_3($m) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::execute@320");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp = Type::getClass($m);
		$b = _hx_anonymous(array("methodName" => "requestIn", "lineNumber" => -1, "fileName" => "", "customParams" => (new _hx_array(array())), "className" => Type::getClassName($tmp)));
		$this1 = null;
		$f = (isset($m->requestIn) ? $m->requestIn: array($m, "requestIn"));
		$tmp1 = array(new _hx_lambda(array(&$f), "ufront_app_HttpApplication_18"), 'execute');
		$this1 = new tink_core_MPair($tmp1, $b);
		{
			$tmp2 = $this1;
			$GLOBALS['%s']->pop();
			return $tmp2;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_4($m1) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::execute@326");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp2 = Type::getClass($m1);
		$b1 = _hx_anonymous(array("methodName" => "handleRequest", "lineNumber" => -1, "fileName" => "", "customParams" => (new _hx_array(array())), "className" => Type::getClassName($tmp2)));
		$this2 = null;
		$f1 = (isset($m1->handleRequest) ? $m1->handleRequest: array($m1, "handleRequest"));
		$tmp3 = array(new _hx_lambda(array(&$f1), "ufront_app_HttpApplication_19"), 'execute');
		$this2 = new tink_core_MPair($tmp3, $b1);
		{
			$tmp = $this2;
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_5($m2) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::execute@332");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp4 = Type::getClass($m2);
		$b2 = _hx_anonymous(array("methodName" => "requestOut", "lineNumber" => -1, "fileName" => "", "customParams" => (new _hx_array(array())), "className" => Type::getClassName($tmp4)));
		$this3 = null;
		$f2 = (isset($m2->responseOut) ? $m2->responseOut: array($m2, "responseOut"));
		$tmp5 = array(new _hx_lambda(array(&$f2), "ufront_app_HttpApplication_20"), 'execute');
		$this3 = new tink_core_MPair($tmp5, $b2);
		{
			$tmp = $this3;
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_6(&$_gthis, $m3) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::execute@338");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp6 = Type::getClass($m3);
		$b3 = _hx_anonymous(array("methodName" => "log", "lineNumber" => -1, "fileName" => "", "customParams" => (new _hx_array(array("httpContext", "appMessages"))), "className" => Type::getClassName($tmp6)));
		$this4 = null;
		$f3 = (isset($m3->log) ? $m3->log: array($m3, "log"));
		$a2 = $_gthis->messages;
		$tmp7 = array(new _hx_lambda(array(&$a2, &$f3), "ufront_app_HttpApplication_21"), 'execute');
		$this4 = new tink_core_MPair($tmp7, $b3);
		{
			$tmp = $this4;
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_7(&$_gthis, &$httpContext, &$logHandModules, &$reqHandModules, &$reqMidModules, &$resMidModules, $n) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::execute@352");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp9 = $_gthis->executeModules($reqMidModules, $httpContext, ufront_web_context_RequestCompletion::$CRequestMiddlewareComplete);
		{
			$tmp = tink_core__Future_Future_Impl_::_tryFailingFlatMap($tmp9, array(new _hx_lambda(array(&$_gthis, &$httpContext, &$logHandModules, &$reqHandModules, &$resMidModules), "ufront_app_HttpApplication_22"), 'execute'));
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_8(&$httpContext) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::execute@361");
		$__hx__spos = $GLOBALS['%s']->length;
		$httpContext->getRequestUri();
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_9(&$f4, $r) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::execute@361");
		$__hx__spos = $GLOBALS['%s']->length;
		call_user_func($f4);
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_10(&$_gthis, &$ctx, &$done, &$flag, &$modules, &$runNext) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::executeModules@403");
		$__hx__spos = $GLOBALS['%s']->length;
		$m = $modules->shift();
		$tmp = null;
		if($flag !== null) {
			$tmp = ($ctx->completion & 1 << $flag->index) !== 0;
		} else {
			$tmp = false;
		}
		if($tmp) {
			$result = tink_core_Outcome::Success(tink_core_Noise::$Noise);
			if($done->{"list"} !== null) {
				$list = $done->{"list"};
				$done->{"list"} = null;
				$done->result = $result;
				tink_core__Callback_CallbackList_Impl_::invoke($list, $result);
				tink_core__Callback_CallbackList_Impl_::clear($list);
			}
		} else {
			if($m === null) {
				if($flag !== null) {
					$ctx->completion |= 1 << $flag->index;
				}
				{
					$result1 = tink_core_Outcome::Success(tink_core_Noise::$Noise);
					if($done->{"list"} !== null) {
						$list1 = $done->{"list"};
						$done->{"list"} = null;
						$done->result = $result1;
						tink_core__Callback_CallbackList_Impl_::invoke($list1, $result1);
						tink_core__Callback_CallbackList_Impl_::clear($list1);
					}
				}
			} else {
				$moduleCb = (isset($m->a) ? $m->a: array($m, "a"));
				$_gthis->currentModule = $m->b;
				$moduleResult = null;
				try {
					$moduleResult = call_user_func_array($moduleCb, array($ctx));
				}catch(Exception $__hx__e) {
					$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
					$e = $_ex_;
					{
						$GLOBALS['%e'] = (new _hx_array(array()));
						while($GLOBALS['%s']->length >= $__hx__spos) {
							$GLOBALS['%e']->unshift($GLOBALS['%s']->pop());
						}
						$GLOBALS['%s']->push($GLOBALS['%e'][0]);
						$tmp1 = Std::string($e);
						$ctx->messages->push(_hx_anonymous(array("msg" => "Caught error " . _hx_string_or_null($tmp1) . " while executing module " . _hx_string_or_null($_gthis->currentModule->className) . "." . _hx_string_or_null($_gthis->currentModule->methodName) . " in HttpApplication.executeModules()", "pos" => _hx_anonymous(array("fileName" => "HttpApplication.hx", "lineNumber" => 422, "className" => "ufront.app.HttpApplication", "methodName" => "executeModules")), "type" => ufront_log_MessageType::$MLog)));
						$tmp2 = ufront_web_HttpError::wrap($e, null, $_gthis->currentModule);
						$tmp3 = tink_core_Outcome::Failure($tmp2);
						$moduleResult = tink_core__Future_Future_Impl_::sync($tmp3);
					}
				}
				$moduleResult(array(new _hx_lambda(array(&$_gthis, &$ctx, &$done, &$runNext), "ufront_app_HttpApplication_23"), 'execute'));
			}
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_11(&$err, $m) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::handleError@450");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp1 = $err->toString();
		$args = (new _hx_array(array($tmp1)));
		$tmp2 = Type::getClass($m);
		$b = _hx_anonymous(array("methodName" => "handleError", "lineNumber" => -1, "fileName" => "", "customParams" => $args, "className" => Type::getClassName($tmp2)));
		$this1 = null;
		$f = (isset($m->handleError) ? $m->handleError: array($m, "handleError"));
		$a1 = $err;
		$tmp3 = array(new _hx_lambda(array(&$a1, &$f), "ufront_app_HttpApplication_24"), 'execute');
		$this1 = new tink_core_MPair($tmp3, $b);
		{
			$tmp = $this1;
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_12($m1) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::handleError@456");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp4 = Type::getClass($m1);
		$b1 = _hx_anonymous(array("methodName" => "requestOut", "lineNumber" => -1, "fileName" => "", "customParams" => (new _hx_array(array())), "className" => Type::getClassName($tmp4)));
		$this2 = null;
		$f1 = (isset($m1->responseOut) ? $m1->responseOut: array($m1, "responseOut"));
		$tmp5 = array(new _hx_lambda(array(&$f1), "ufront_app_HttpApplication_25"), 'execute');
		$this2 = new tink_core_MPair($tmp5, $b1);
		{
			$tmp = $this2;
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_13(&$_gthis, $m2) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::handleError@462");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp6 = Type::getClass($m2);
		$b2 = _hx_anonymous(array("methodName" => "log", "lineNumber" => -1, "fileName" => "", "customParams" => (new _hx_array(array("httpContext", "appMessages"))), "className" => Type::getClassName($tmp6)));
		$this3 = null;
		$f2 = (isset($m2->log) ? $m2->log: array($m2, "log"));
		$a21 = $_gthis->messages;
		$tmp7 = array(new _hx_lambda(array(&$a21, &$f2), "ufront_app_HttpApplication_26"), 'execute');
		$this3 = new tink_core_MPair($tmp7, $b2);
		{
			$tmp = $this3;
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_14(&$ctx, $n) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::handleError@470");
		$__hx__spos = $GLOBALS['%s']->length;
		$ctx->completion |= 1 << ufront_web_context_RequestCompletion::$CRequestHandlersComplete->index;
		{
			$tmp = ufront_core_SurpriseTools::success();
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_15(&$_gthis, &$ctx, &$logHandModules, &$resMidModules, $n1) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::handleError@475");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp10 = $_gthis->executeModules($resMidModules, $ctx, ufront_web_context_RequestCompletion::$CResponseMiddlewareComplete);
		{
			$tmp = tink_core__Future_Future_Impl_::_tryFailingFlatMap($tmp10, array(new _hx_lambda(array(&$_gthis, &$ctx, &$logHandModules), "ufront_app_HttpApplication_27"), 'execute'));
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_16(&$doneTrigger, &$err) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::handleError@480");
		$__hx__spos = $GLOBALS['%s']->length;
		$result = tink_core_Outcome::Failure($err);
		if($doneTrigger->{"list"} !== null) {
			$list = $doneTrigger->{"list"};
			$doneTrigger->{"list"} = null;
			$doneTrigger->result = $result;
			tink_core__Callback_CallbackList_Impl_::invoke($list, $result);
			tink_core__Callback_CallbackList_Impl_::clear($list);
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_17(&$f3, $r) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::handleError@480");
		$__hx__spos = $GLOBALS['%s']->length;
		call_user_func($f3);
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_18(&$f, $a1) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::setContentDirectory@321");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = call_user_func_array($f, array($a1));
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_19(&$f1, $a11) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::setContentDirectory@327");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = call_user_func_array($f1, array($a11));
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_20(&$f2, $a12) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::setContentDirectory@333");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = call_user_func_array($f2, array($a12));
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_21(&$a2, &$f3, $a13) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::setContentDirectory@339");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = call_user_func_array($f3, array($a13, $a2));
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_22(&$_gthis, &$httpContext, &$logHandModules, &$reqHandModules, &$resMidModules, $n1) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::setContentDirectory@353");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp10 = $_gthis->executeModules($reqHandModules, $httpContext, ufront_web_context_RequestCompletion::$CRequestHandlersComplete);
		{
			$tmp = tink_core__Future_Future_Impl_::_tryFailingFlatMap($tmp10, array(new _hx_lambda(array(&$_gthis, &$httpContext, &$logHandModules, &$resMidModules), "ufront_app_HttpApplication_28"), 'execute'));
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_23(&$_gthis, &$ctx, &$done, &$runNext, $result2) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::setContentDirectory@425");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp4 = $result2->index;
		switch($tmp4) {
		case 0:{
			call_user_func($runNext);
		}break;
		case 1:{
			$_gthis->handleError(_hx_deref($result2)->params[0], $ctx, $done);
		}break;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_24(&$a1, &$f, $a2) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::setContentDirectory@451");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = call_user_func_array($f, array($a1, $a2));
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_25(&$f1, $a11) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::setContentDirectory@457");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = call_user_func_array($f1, array($a11));
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_26(&$a21, &$f2, $a12) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::setContentDirectory@463");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = call_user_func_array($f2, array($a12, $a21));
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_27(&$_gthis, &$ctx, &$logHandModules, $n2) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::setContentDirectory@476");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp11 = $_gthis->executeModules($logHandModules, $ctx, ufront_web_context_RequestCompletion::$CLogHandlersComplete);
		{
			$tmp = tink_core__Future_Future_Impl_::_tryFailingFlatMap($tmp11, array(new _hx_lambda(array(&$_gthis, &$ctx), "ufront_app_HttpApplication_29"), 'execute'));
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_28(&$_gthis, &$httpContext, &$logHandModules, &$resMidModules, $n2) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::setContentDirectory@354");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp11 = $_gthis->executeModules($resMidModules, $httpContext, ufront_web_context_RequestCompletion::$CResponseMiddlewareComplete);
		{
			$tmp = tink_core__Future_Future_Impl_::_tryFailingFlatMap($tmp11, array(new _hx_lambda(array(&$_gthis, &$httpContext, &$logHandModules), "ufront_app_HttpApplication_30"), 'execute'));
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_29(&$_gthis, &$ctx, $n3) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::setContentDirectory@477");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp12 = $_gthis->clearMessages();
		{
			$tmp = tink_core__Future_Future_Impl_::_tryMap($tmp12, array(new _hx_lambda(array(&$_gthis, &$ctx), "ufront_app_HttpApplication_31"), 'execute'));
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_30(&$_gthis, &$httpContext, &$logHandModules, $n3) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::setContentDirectory@355");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp12 = $_gthis->executeModules($logHandModules, $httpContext, ufront_web_context_RequestCompletion::$CLogHandlersComplete);
		{
			$tmp = tink_core__Future_Future_Impl_::_tryFailingFlatMap($tmp12, array(new _hx_lambda(array(&$_gthis, &$httpContext), "ufront_app_HttpApplication_32"), 'execute'));
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_31(&$_gthis, &$ctx, $n4) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::setContentDirectory@478");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = $_gthis->flush($ctx);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_32(&$_gthis, &$httpContext, $n4) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::setContentDirectory@356");
		$__hx__spos = $GLOBALS['%s']->length;
		$tmp13 = $_gthis->clearMessages();
		{
			$tmp = tink_core__Future_Future_Impl_::_tryMap($tmp13, array(new _hx_lambda(array(&$_gthis, &$httpContext), "ufront_app_HttpApplication_33"), 'execute'));
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
function ufront_app_HttpApplication_33(&$_gthis, &$httpContext, $n5) {
	{
		$GLOBALS['%s']->push("ufront.app.HttpApplication::setContentDirectory@357");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$tmp = $_gthis->flush($httpContext);
			$GLOBALS['%s']->pop();
			return $tmp;
		}
		$GLOBALS['%s']->pop();
	}
}
