<?php

// Generated by Haxe 3.3.0
class tink_core__Any_Any_Impl_ {
	public function __construct(){}
	static function __promote($this1) {
		$GLOBALS['%s']->push("tink.core._Any.Any_Impl_::__promote");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$GLOBALS['%s']->pop();
			return $this1;
		}
		$GLOBALS['%s']->pop();
	}
	function __toString() { return 'tink.core._Any.Any_Impl_'; }
}
